### PR TITLE
Update to r21

### PR DESCRIPTION
**Pull request by vok1980**

### CODE REVIEW

**Comment by vok1980** [comment]
Target branch needs to be corrected.

**Comment by Croydon** [comment]
Is Windows 32bit support official removed by upstream?
If Clang < 9 support official removed by upstream?

Could you please point me to some document saying this?

**Comment by cajus** [comment]
For whatever reason it's clang 9.0 instead of 9 for me.

**Comment by vok1980** [comment]
> Is Windows 32bit support official removed by upstream?
> Could you please point me to some document saying this?

32-bit Windows is no longer supported. This does not affect the vast majority of users. If you do still need to build NDK apps from 32-bit versions of Windows, continue using NDK r20.
https://github.com/android/ndk/wiki/Changelog-r21

**Comment by vok1980** [comment]
> If Clang < 9 support official removed by upstream?
> Could you please point me to some document saying this?

Updated Clang and LLD to r365631.
see https://github.com/crDroidMod/android_prebuilts_clang_host_linux-x86_clang-5799447
https://github.com/android/ndk/wiki/Changelog-r21

**Comment by vok1980** [comment]
@rikdev , FYI

**Review by Croydon — CHANGES_REQUESTED** [review]
Please remove the two `.travis.yml` entries related to `ARCH=x86`

**Comment by vok1980** [comment]
> Please remove the two `.travis.yml` entries related to `ARCH=x86`

I guess, you mean 'ARCH_BUILD: x86', not 'ARCH'.

**Comment by vok1980** [comment]
BTW, guys, you have `settings['compiler.libcxx'] = 'libc++'` in `build.py` and simultaneously 
```
if not str(self.settings.compiler.libcxx) in ["c++_shared", "c++_static"]:
            raise ConanInvalidConfiguration("only libc++ standard library is supported")
``` 
in `conanfile.py`. One of this need to be fixed. Please, see #7 

You can see travis now reporting:
> Skipped configuration by the recipe: android_ndk_installer/r21@bincrafters/testing: Invalid configuration: only libc++ standard library is supported

**Review by SSE4 — APPROVED** [review]

**Comment by Croydon** [comment]
> I guess, you mean 'ARCH_BUILD: x86', not 'ARCH'.

No, I meant `ARCH` because I was talking about the `.travis.yml` file not the `appveyor.yml`

**Comment by vok1980** [comment]
> > I guess, you mean 'ARCH_BUILD: x86', not 'ARCH'.
> 
> No, I meant `ARCH` because I was talking about the `.travis.yml` file not the `appveyor.yml`

There is no reason to remove `ARCH x86`. Android x86 arch still supported. 
32-bit Windows is no longer supported -- it means that we can't build on 32-bit windows. In terms of conan, `ARCH_BUILD x86` for `PLATFORM windows` need to be removed. 
I see, you removed `ARCH x86` for linux and osx in `.travis.yml` in commit 0f1e9c405f73267eb500cb60f66eaf4f167fc89b. Please revert it.
@SSE4 FYI

**Comment by SSE4** [comment]
right, I'll revert

**Pull request merged**
